version: "3.6"

services:
  skeleton_db:
    image: mysql:5.7
    volumes:
      - dbvol:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=skeleton
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
    ports:
      - 5432:3306

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DB_USER: "${DB_USER:-root}"
        DB_PASSWORD: "${DB_PASSWORD:-password}"
        DB_URL: "${DB_URL:-jdbc:mysql://host.docker.internal:5432/skeleton}"
    container_name: skeleton_service
    environment:
      - PROFILE=local
      - DB_URL=jdbc:mysql://skeleton_db:3306/skeleton
      - DB_USER=root
      - DB_PASSWORD=password
      - DATABASE_NAME=skeleton
      - DATABASE_PORT=3306
      - DATABASE_HOST=skeleton_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - CACHE_HOST=host.docker.internal
      - CACHE_PORT=6379
    volumes:
      - /app
    ports:
      - 8084:8080
    tty: true
    stdin_open: true
    depends_on:
      - skeleton_db

volumes:
  dbvol: {}
